services:
  postgres:
    image: postgres
    container_name: postgres_insurance
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-insurance}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-insurance254}
      POSTGRES_DB: ${POSTGRES_DB:-insurancedb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - insurancenetwork

volumes:
  pgdata:

networks:
  insurancenetwork:
